project_id = "cuqjaddtmkotgvfsgcol"

[functions.export-data]
verify_jwt = false

[functions.force-password-reset]
verify_jwt = false

[functions.sign-out-all-users]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.generate-profile-avatars]
verify_jwt = false
